using System.Collections.Generic;

using UnityEngine;

using Engine.Animation;
using Engine.Utility;

namespace Engine.UI.Bitty {

    // One motion token = one named transition. Materializes into a TweenPreset.
    public class UIMotionToken {

        public float time = .45f;
        public float delay = 0f;
        public string ease = "quadEaseInOut";
        public bool fade = true;
    }

    // The token source: the single authority for palette, sizing, fonts, and motion.
    //
    // Two materializers consume it, and that is the whole point of having it:
    //   * TweenPresets  <- the `motion` block (wired here, in Seed())
    //   * vars.uss      <- generated by the UI Toolkit backend's theme step (chunk 2.7)
    // A future backend materializes the same tokens its own way. Durations and eases live
    // in data, so tuning a transition is a data edit, not a code edit — which is what kills
    // the scattered hard-coded ±4500-unit slides and magic .45f/.5f literals.
    //
    // Defaults below are seeded from the legacy TweenUtil constants so Phase 3 starts at
    // TODAY's timings and tunes from there. Content overrides them by shipping a tokens.json
    // (chunk 2.7); until then the built-in defaults are the whole theme.
    public class UITokens {

        public const string defaultResourcePath = "ui/tokens";

        public Dictionary<string, string> color = new Dictionary<string, string>();
        public Dictionary<string, float> size = new Dictionary<string, float>();
        public Dictionary<string, string> font = new Dictionary<string, string>();
        public Dictionary<string, UIMotionToken> motion = new Dictionary<string, UIMotionToken>();

        private static UITokens _current = null;

        public static UITokens current {
            get {

                if (_current == null) {
                    _current = Defaults();
                    _current.Seed();
                }

                return _current;
            }
        }

        // Legacy-faithful defaults. The motion values are exactly TweenUtil's constants
        // (durationShow .45 / durationDelayShow .5 / durationHide .45 / durationDelayHide 0)
        // and TweenPresets' seeded table, so swapping presets on changes nothing visually.
        public static UITokens Defaults() {

            UITokens t = new UITokens();

            t.color["panel-bg"] = "#2D2D2D";
            t.color["text-primary"] = "#E0E0E0";

            t.size["gap-m"] = 16f;
            t.size["radius-m"] = 8f;

            t.motion["panel-show"] = Motion(.45f, .5f);
            t.motion["panel-hide"] = Motion(.45f, 0f);
            t.motion["dialog-show"] = Motion(.3f, 0f);
            t.motion["dialog-hide"] = Motion(.3f, 0f);
            t.motion["fade-in"] = Motion(.5f, 0f);
            t.motion["fade-out"] = Motion(.5f, 0f);
            t.motion["hud-show"] = Motion(.45f, .5f);
            t.motion["hud-hide"] = Motion(.45f, 0f);

            return t;
        }

        private static UIMotionToken Motion(float time, float delay) {

            UIMotionToken m = new UIMotionToken();
            m.time = time;
            m.delay = delay;

            return m;
        }

        // Load from a Resources-hosted tokens.json. Missing file is not an error — the
        // built-in defaults stand, so the platform boots with a coherent theme either way.
        public static bool Load(string resourcePath = defaultResourcePath) {

            TextAsset asset = Resources.Load<TextAsset>(resourcePath);

            if (asset == null) {
                LogUtil.Log("UITokens: no token file at Resources/" + resourcePath
                    + " — using built-in defaults");
                return false;
            }

            return LoadFromJson(asset.text);
        }

        public static bool LoadFromJson(string json) {

            if (string.IsNullOrEmpty(json)) {
                return false;
            }

            UITokens parsed = null;

            try {
                parsed = json.FromJson<UITokens>();
            }
            catch (System.Exception e) {
                LogUtil.LogError("UITokens: token parse failed, keeping defaults: " + e.Message);
                return false;
            }

            if (parsed == null) {
                return false;
            }

            // Merge onto defaults rather than replace: a token file that only overrides two
            // colors must not blank out the motion table.
            UITokens merged = Defaults();

            Merge(merged.color, parsed.color);
            Merge(merged.size, parsed.size);
            Merge(merged.font, parsed.font);
            Merge(merged.motion, parsed.motion);

            _current = merged;
            _current.Seed();

            return true;
        }

        private static void Merge<T>(Dictionary<string, T> into, Dictionary<string, T> from) {

            if (from == null) {
                return;
            }

            foreach (KeyValuePair<string, T> pair in from) {
                into[pair.Key] = pair.Value;
            }
        }

        // The wiring TweenPresets has been waiting for. TweenPresets shipped in Phase 1 with a
        // comment naming this chunk as its future authority and zero call sites; this is that
        // authority arriving. After Seed(), TweenPresets.Get("panel-show") returns the token
        // value, so panel transitions are data-driven without a single call site changing.
        public void Seed() {

            foreach (KeyValuePair<string, UIMotionToken> pair in motion) {

                UIMotionToken m = pair.Value;

                TweenPresets.Set(new TweenPreset(
                    pair.Key, m.time, m.delay, ParseEase(m.ease), TweenLoopType.once, m.fade));
            }
        }

        // Unknown ease names fall back to the engine default rather than throwing — a typo in
        // a token file should not take the UI down.
        public static TweenEaseType ParseEase(string ease) {

            if (ease == "linear") {
                return TweenEaseType.linear;
            }
            else if (ease == "quadEaseIn") {
                return TweenEaseType.quadEaseIn;
            }
            else if (ease == "quadEaseOut") {
                return TweenEaseType.quadEaseOut;
            }
            else if (ease == "quadEaseInOut") {
                return TweenEaseType.quadEaseInOut;
            }

            if (!string.IsNullOrEmpty(ease)) {
                LogUtil.LogWarning("UITokens: unknown ease '" + ease + "', using quadEaseInOut");
            }

            return TweenEaseType.quadEaseInOut;
        }

        // ACCESSORS
        // Never throw on a missing token — return the supplied fallback. A missing token is a
        // content bug that should show up as a wrong color, not as a crash mid-panel.

        public Color GetColor(string key, Color fallback) {

            string hex = null;

            if (!color.TryGetValue(key, out hex) || string.IsNullOrEmpty(hex)) {
                return fallback;
            }

            Color parsed = Color.white;

            if (!ColorUtility.TryParseHtmlString(hex, out parsed)) {
                LogUtil.LogWarning("UITokens: bad color '" + hex + "' for '" + key + "'");
                return fallback;
            }

            return parsed;
        }

        public float GetSize(string key, float fallback) {

            float val = 0f;

            if (!size.TryGetValue(key, out val)) {
                return fallback;
            }

            return val;
        }

        public string GetFont(string key, string fallback) {

            string val = null;

            if (!font.TryGetValue(key, out val) || string.IsNullOrEmpty(val)) {
                return fallback;
            }

            return val;
        }

        public UIMotionToken GetMotion(string key) {

            UIMotionToken val = null;

            if (!motion.TryGetValue(key, out val) || val == null) {
                return motion["panel-show"];
            }

            return val;
        }
    }
}
